
#' function to calculate F1 score
#' @param simulate result from simulateGraph
#' @param result result from any of the jointnets method using the samples generated by simulate
#' @return a list of F1 scores between simulate and result between 0 and 1 (higher scores correspond to better estimation)
#' @details scores' order correspond to task order and the last score in the list represent score for shared graph (only applicable to simule and wsimule)
F1 <- function(simulate, result) {
  K = length(simulate$graphs)
  hasshare = !is.null(result$share)
  simulate = make_adj_matrix(simulate,TRUE)
  result = make_adj_matrix(result,TRUE)
  f1 = c()
  for (i in 1:K) {
    f1[i] = F1_single(simulate[[i]],result[[i]])
  }

  if (hasshare){
    f1[K+1] = F1_single(simulate$share,result$share)
  }

  ### need to revise on this to adapt to diffee
  return(f1)
}

#' function to calculate F1 score for a single simulate graph with a single result graph
#' @param simulate single precision matrix of simulateGraph
#' @param result single corresponding precision matrix generated by any of the jointnets method
#' @return a single F1 score between simulate and result between 0 and 1 (higher scores correspond to better estimation)
F1_single <- function(simulate,result){
  tP = sum((result == 1) & (simulate == 1))
  tN = sum((result == 0) & (simulate == 0))
  fP = sum((result == 1) & (simulate == 0))
  fN = sum((result == 0) & (simulate == 1))
  pPM = tP / (tP + fP)
  rPM = tP / (tP + fN)
  return(2 * pPM * rPM / (pPM + rPM))
}
